version: '3.5'

services:
  telegram-db-bot:
    image: mitto98/telegram-downloader-bot:latest
    environment:
      TELEGRAM_BOT_TOKEN: "6836264981:AAGd2EPZXoHuZK4B5TxjcgbcwgBnFUtE8w8"
      TELEGRAM_CHAT_ID: "@dogdwlbot"
    volumes:
       - ./downloads:/downloads
    restart: unless-stopped
